name: build

on:
  push:
    paths:
    - 'ult/**'
jobs:
  latex-job:
    runs-on: ubuntu-latest
    name: Latex Job
    steps:
    - uses: actions/checkout@v1
    - name: Compile
      uses: vinay0410/tectonic-action@master
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tex_path: 'ult/main.tex'
    - name: Upload PDF
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ult/main.pdf
        asset_name: stl.pdf
        tag: b
        overwrite: true
        prerelease: true
